# Generated by Django 3.0.5 on 2020-04-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Class',
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'db_table': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='TrainingSystemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Training system',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=128)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.ClassModel')),
            ],
            options={
                'verbose_name': 'Student',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_first', models.IntegerField(default=0)),
                ('score_second', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.StudentModel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.SubjectModel')),
            ],
            options={
                'verbose_name': 'Score',
                'db_table': 'Score',
            },
        ),
        migrations.AddField(
            model_name='classmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseModel'),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.FacultyModel'),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='training_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.TrainingSystemModel'),
        ),
    ]
