# Generated by Django 3.0.5 on 2020-04-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultymodel',
            options={'verbose_name': 'Faculty'},
        ),
        migrations.AlterModelTable(
            name='facultymodel',
            table='Faculty',
        ),
    ]
