# Generated by Django 3.0.5 on 2020-04-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_first', models.IntegerField(default=0)),
                ('score_second', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentModel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectModel')),
            ],
        ),
    ]
