# Generated by Django 3.0.5 on 2020-04-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoremodel',
            options={'verbose_name': 'Score'},
        ),
        migrations.AlterModelTable(
            name='scoremodel',
            table='Score',
        ),
    ]
