# Generated by Django 3.0.5 on 2020-04-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsystemmodel',
            old_name='raining_name',
            new_name='training_name',
        ),
        migrations.AlterModelTable(
            name='trainingsystemmodel',
            table='Hệ đào tạo',
        ),
    ]
