# Generated by Django 3.0.5 on 2020-04-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200414_1707'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainingsystemmodel',
            table=None,
        ),
    ]
