# Generated by Django 3.0.5 on 2020-04-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200414_1710'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainingsystemmodel',
            table='Hệ đào tạo',
        ),
    ]
