# Generated by Django 3.0.5 on 2020-04-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200414_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsystemmodel',
            options={'verbose_name': 'Hệ đào tạo'},
        ),
    ]
