# Generated by Django 3.0.5 on 2020-04-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200414_1721'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainingsystemmodel',
            table='trainingsystem',
        ),
    ]
