# Generated by Django 3.0.5 on 2020-04-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200414_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classmodel',
            options={'verbose_name': 'Class'},
        ),
        migrations.AlterModelOptions(
            name='trainingsystemmodel',
            options={'verbose_name': 'Training system'},
        ),
        migrations.AlterModelTable(
            name='classmodel',
            table='Class',
        ),
    ]
