# Generated by Django 3.0.5 on 2020-04-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=255)),
                ('sex', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassModel')),
            ],
        ),
    ]
