# Generated by Django 3.0.5 on 2020-04-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentmodel',
            table='student',
        ),
    ]
