# Generated by Django 3.0.5 on 2020-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200414_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='sex',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=128),
        ),
    ]
