# Generated by Django 3.0.5 on 2020-04-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200414_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'verbose_name': 'Student'},
        ),
    ]
