# Generated by Django 3.0.5 on 2020-04-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmodel',
            options={'verbose_name': 'Subject'},
        ),
        migrations.AlterModelTable(
            name='subjectmodel',
            table='subject',
        ),
    ]
